java_test(
    name = "AutoBoxing",
    srcs = ["AutoBoxing.java"],
    tags = ["skip"]  # TODO
)

java_test(
    name = "MetricsApiTest",
    srcs = ["MetricsApiTest.java"],
    deps = [
        "@maven2//:com_codahale_metrics_metrics_core",
   ]
)
