title: Remember Java
email: webmail5@hblok.net
description: >
  Java Programming Tips & Tricks.
  Snippets of code to learn, understand and explore.
baseurl: ""
url: "http://rememberjava.com"
github_username:  hblok

# Build settings
paginate: 8
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - bazel-bin
  - bazel-out
  - bazel-rememberjava
  - bazel-testlogs
  - dist

