java_library(
    name = "midi",
    srcs = [
        "AbstractMessage.java",
        "MidiUtils.java",
	"RawMessage.java",
    ],
)

# TOOD: Fix paths
# java_test(
#     name = "MidiApiTest",
#     srcs = ["MidiApiTest.java"],
#     deps = [":midi"]
# )

