java_test(
    name = "BitcoinjApiTest",
    srcs = ["BitcoinjApiTest.java"],
    size = "large",
    tags = ["skip"],  # Too large
    deps = [
	"@maven2//:com_google_guava_guava",
	"@maven2//:org_slf4j_slf4j_simple",
        "@maven2//:org_bitcoinj_bitcoinj_core",
    ]
)
