java_binary(
    name = "FileIoIdeas",
    srcs = ["FileIoIdeas.java"]
)

java_test(
    name = "GenericConstructor",
    srcs = ["GenericConstructor.java"]
)

java_test(
    name = "IdentityCollectorsTest",
    srcs = ["IdentityCollectorsTest.java"]
)

java_test(
    name = "ParallelCount",
    srcs = ["ParallelCount.java"]
)

java_test(
    name = "StreamFun",
    srcs = ["StreamFun.java"],
    tags = ["skip"],
)

java_test(
    name = "WordCount",
    srcs = ["WordCount.java"],
    data = ["words"]
)

java_test(
    name = "WordCountAlt",
    srcs = ["WordCountAlt.java"]
)

