java_test(
    name = "PrimitiveTypes",
    srcs = ["PrimitiveTypes.java"]
)

java_binary(
    name = "ThreadFunction",
    srcs = ["ThreadFunction.java"]
)

java_binary(
    name = "ThreadsInline",
    srcs = ["ThreadsInline.java"]
)

java_binary(
    name = "ThreadsOldSchool",
    srcs = ["ThreadsOldSchool.java"]
)

java_test(
    name = "TryCatchTest",
    srcs = ["TryCatchTest.java"]
)
