# Usage examples:
#
# bazel test ...
# bazel test :HelloJunit

java_test(
    name = "ExceptionsTest",
    srcs = ["ExceptionsTest.java"],
)

java_test(
    name = "HelloJunit",
    srcs = ["HelloJunit.java"],
)

java_test(
    name = "JunitTestMethods",
    srcs = ["JunitTestMethods.java"],
)

java_test(
    name = "JunitTestMethodsOrder",
    srcs = ["JunitTestMethodsOrder.java"],
)